import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ExternalLink from '../public/external-link.svg'
import Github from '../public/github.svg'
import Safe from '../public/safe.svg'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Safe Tutorial: Passkeys',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            padding: '1rem'
          }}
        >
          <a href="https://safe.global">
            <Safe width={95} height={36} />
          </a>
          <div style={{ display: 'flex' }}>
            <a
              href="https://docs.safe.global/home/passkeys-tutorials/safe-passkeys-tutorial"
              style={{
                display: 'flex',
                alignItems: 'center',
                marginRight: '1rem'
              }}
              target="_blank"
              rel="noopener noreferrer"
            >
              Read tutorial <ExternalLink style={{ marginLeft: '0.5rem' }} />
            </a>
            <a
              href="https://github.com/5afe/safe-passkeys-tutorial"
              style={{ display: 'flex', alignItems: 'center' }}
              target="_blank"
              rel="noopener noreferrer"
            >
              View on GitHub{' '}
              <Github width={24} height={24} style={{ marginLeft: '0.5rem' }} />
            </a>
          </div>
        </nav>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginLeft: '40px',
            marginRight: '40px',
            flexDirection: 'column'
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
