name: Weekly update for supported networks

on:
  schedule:
  - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  generate-supported-networks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320  # v5.0.0

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Generate supported networks
        run: pnpm generate-supported-networks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
