name: Style check

on: pull_request

jobs:
  vale-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0

      - name: Vale Linter
        uses: vale-cli/vale-action@d89dee975228ae261d22c15adcd03578634d429c  # v2.1.1
        with:
          vale_flags: "--glob=pages/**/*.{md,mdx} --minAlertLevel=error"
          fail_on_error: true
