name: Style check
on: pull_request

jobs:
  vale-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--glob=pages/**/*.{md,mdx} --minAlertLevel=error"
          fail_on_error: true
