name: Weekly link check

on:
  schedule:
  - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        folder-path: './'
        config-file: 'linkchecker-config.json'
        base-branch: 'main'
    - name: Create Issue
      if: ${{ failure() }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh issue create \
          --title "Link Checker Report" \
          --label "report" \
          --label "automated issue" \
          --body "Broken links found: [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Workflow: \`${{ github.workflow }}\`"
